Repository nennigb/amc2moodle, pull requests merged in 2025-03, with the labels that each got.

#99 add new workflow to publish on PyPI and generate releases on github
  .github/workflows/build-container.yml
  .github/workflows/ci-publish.yml
Labels: enhancement, ci, deployment

#100 Bump version to 2.12.1.
  amc2moodle/_version.py
Labels: ci, deployment

#101 Add missing `needs` on pypi publish ci.
  .github/workflows/ci-publish.yml
Labels: ci, deployment

#103 Add new features in build workflow to build arm64 container
  .github/workflows/build-container.yml
Labels: enhancement, docker, ci, deployment
